Repository andrewdimmer/help-hub, pull requests merged in 2020-04, with the labels that each got.

#1 feat(front-end): Initialized Front End
  .vscode/extensions.json
  .vscode/settings.json
  front-end/.gitignore
  front-end/README.md
  front-end/package-lock.json
  front-end/package.json
  front-end/public/favicon.ico
  front-end/public/index.html
  front-end/public/logo192.png
  front-end/public/logo512.png
  front-end/public/manifest.json
  front-end/public/robots.txt
  front-end/src/App.tsx
  front-end/src/Components/Layouts/NavBar.tsx
  front-end/src/Components/Misc/LoadingScreen.tsx
  front-end/src/Components/Misc/Notifications.tsx
  front-end/src/Components/Pages/HomePage.tsx
  front-end/src/Styles/index.ts
  front-end/src/Styles/theme.ts
  front-end/src/Styles/useDarkMode.ts
  front-end/src/index.css
  front-end/src/index.tsx
  front-end/src/react-app-env.d.ts
  front-end/src/serviceWorker.ts
  front-end/src/setupTests.ts
  front-end/tsconfig.json
Labels: enhancement

#2 feat: Added Login and Profile Update Systems
  .firebaserc
  .gitignore
  firebase.json
  front-end/package-lock.json
  front-end/package.json
  front-end/src/App.tsx
  front-end/src/Components/App.tsx
  front-end/src/Components/Content/LoginUi.tsx
  front-end/src/Components/Content/ProfileInformation/ViewEditUserDisplayName.tsx
  front-end/src/Components/Content/ProfileInformation/ViewEditUserEmail.tsx
  front-end/src/Components/Content/ProfileInformation/ViewEditUserPassword.tsx
  front-end/src/Components/Content/ProfileInformation/ViewEditUserPhone.tsx
  front-end/src/Components/Content/ProfileInformation/ViewEditUserPhoto.tsx
  front-end/src/Components/Layouts/NavBar.tsx
  front-end/src/Components/Misc/SquareAvatar.tsx
  front-end/src/Components/Pages/ErrorPage.tsx
  front-end/src/Components/Pages/HomePage.tsx
  front-end/src/Components/Pages/LoginPage.tsx
  front-end/src/Components/Pages/LogoutPage.tsx
  front-end/src/Components/Pages/ProfilePage.tsx
  front-end/src/Components/Pages/index.ts
  front-end/src/Scripts/firebaseAuth.ts
  front-end/src/Scripts/firebaseConfig.ts
  front-end/src/Scripts/firebaseCreateNewUser.ts
  front-end/src/Scripts/firebaseGetUserProfile.tsx
  front-end/src/Scripts/firebaseProfileUpdates.ts
  front-end/src/Styles/CustomThemeProvider.tsx
  front-end/src/Styles/index.ts
  front-end/src/index.tsx
  functions/.gitignore
  functions/package-lock.json
  functions/package.json
  functions/src/Firebase/Users/createNewUser.ts
  functions/src/Firebase/Users/getUserProfile.ts
  functions/src/Firebase/Users/testInformationMappings.ts
  functions/src/Firebase/Users/updateUserProfileDatabase.ts
  functions/src/Firebase/Users/userInformationMappings.ts
  functions/src/Firebase/firebaseConfig.ts
  functions/src/Helpers/allSuccessful.ts
  functions/src/Helpers/logErrors.ts
  functions/src/index.ts
  functions/tsconfig.json
  functions/tslint.json
Labels: bug, enhancement

#3 fix(front-end): Connect the Homepage and NavBar to actual pages
  front-end/src/Components/App.tsx
  front-end/src/Components/Layouts/NavBar.tsx
  front-end/src/Components/Pages/HomePage.tsx
  front-end/src/Components/Pages/LoginPage.tsx
Labels: bug

#4 fix(front-end): Added Zip Code to Profile Page
  front-end/src/Components/Content/ProfileInformation/ViewEditUserZipcode.tsx
  front-end/src/Components/Pages/ProfilePage.tsx
  front-end/src/Scripts/firebaseCreateNewUser.ts
  front-end/src/Scripts/firebaseGetUserProfile.tsx
  front-end/src/Scripts/firebaseProfileUpdates.ts
  functions/src/Firebase/Users/createNewUser.ts
  functions/src/Firebase/Users/getUserProfile.ts
  functions/src/Firebase/Users/updateUserProfileDatabase.ts
  functions/src/index.ts
Labels: enhancement

#5 feat(front-end): Connected pages to existing backend
  front-end/src/Components/Content/Categories.tsx
  front-end/src/Components/Layouts/DateTime.tsx
  front-end/src/Components/Layouts/Event.tsx
  front-end/src/Components/Layouts/EventOrg.tsx
  front-end/src/Components/Pages/CreateEvent.tsx
  front-end/src/Components/Pages/EventsPage.tsx
  front-end/src/Components/Pages/ManageEvents.tsx
  front-end/src/Components/Pages/index.ts
Labels: enhancement

#7 feat(front-end): add events page
  front-end/src/Components/Content/Categories.tsx
  front-end/src/Components/Layouts/DateTime.tsx
  front-end/src/Components/Layouts/Event.tsx
  front-end/src/Components/Layouts/EventOrg.tsx
  front-end/src/Components/Pages/CreateEvent.tsx
  front-end/src/Components/Pages/EventsPage.tsx
  front-end/src/Components/Pages/LoginPage.tsx
  front-end/src/Components/Pages/ManageEvents.tsx
  front-end/src/Components/Pages/index.ts
Labels: bug, enhancement

#8 feat(front-end): added state to the create event page
  front-end/src/Components/Layouts/DateTime.tsx
  front-end/src/Components/Pages/CreateEvent.tsx
Labels: bug

#9 fear(front-end): added filters UI
  front-end/src/Components/Pages/EventsPage.tsx
Labels: enhancement

#10 feat(front-end): Can Now Save an Event (at least on the Front End)
  front-end/src/Components/Content/ProfileInformation/ViewEditUserPhone.tsx
  front-end/src/Components/Pages/CreateEvent.tsx
  front-end/src/Scripts/firebaseCreateEvent.ts
Labels: enhancement

#12 feat: Added Data Validation, Filtering by Zip Code and Category, and User Interests
  front-end/package-lock.json
  front-end/package.json
  front-end/src/Components/App.tsx
  front-end/src/Components/Content/Categories.ts
  front-end/src/Components/Content/Categories.tsx
  front-end/src/Components/Content/ProfileInformation/ViewEditUserInterests.tsx
  front-end/src/Components/Layouts/DateTime.tsx
  front-end/src/Components/Pages/CreateEvent.tsx
  front-end/src/Components/Pages/EventsPage.tsx
  front-end/src/Components/Pages/LoginPage.tsx
  front-end/src/Components/Pages/ProfilePage.tsx
  front-end/src/Scripts/firebaseConfig.ts
  front-end/src/Scripts/firebaseCreateNewUser.ts
  front-end/src/Scripts/firebaseProfileUpdates.ts
  front-end/src/Scripts/firebaseUserTypes.d.ts
  functions/package-lock.json
  functions/package.json
  functions/src/Firebase/Events/createNewEvents.ts
  functions/src/Firebase/Events/eventRefMappings.ts
  functions/src/Firebase/Events/getEventsWithinRadius.ts
  functions/src/Firebase/Events/sortEventsByStartDate.ts
  functions/src/Firebase/Users/createNewUser.ts
  functions/src/Firebase/Users/getUserProfile.ts
  functions/src/Firebase/Users/updateUserProfileDatabase.ts
  functions/src/index.ts
Labels: bug, enhancement

#15 feat(functions): Creating, Editing, and Viewing Organizations Works on the Back End
  front-end/src/Scripts/firebaseEventTypes.d.ts
  front-end/src/Scripts/firebaseOrganizationTypes.d.ts
  functions/src/Firebase/Events/createNewEvents.ts
  functions/src/Firebase/Events/eventRefMappings.ts
  functions/src/Firebase/Events/eventTypes.d.ts
  functions/src/Firebase/Events/getEventsByOrganization.ts
  functions/src/Firebase/Events/getEventsFromEventGroupRefCollection.ts
  functions/src/Firebase/Events/getEventsWithinRadius.ts
  functions/src/Firebase/Organizations/createNewOrganization.ts
  functions/src/Firebase/Organizations/getOrganizationProfile.ts
  functions/src/Firebase/Organizations/getOrganizationsByUser.ts
  functions/src/Firebase/Organizations/getOrganizationsFromOrganizationRefCollection.ts
  functions/src/Firebase/Organizations/organizationRefMappings.ts
  functions/src/Firebase/Organizations/organizationTypes.d.ts
  functions/src/Firebase/Organizations/sortOrganizationsByName.ts
  functions/src/Firebase/Organizations/updateOrganizationInformation.ts
  functions/src/Firebase/Users/getUserProfile.ts
  functions/src/Firebase/Users/sortUsersByName.ts
  functions/src/index.ts
Labels: bug, enhancement

#16 feat: Connected the Organization Front End and Back End
  front-end/src/Components/Content/OrganizationInformation/ViewEditOrganizationDescription.tsx
  front-end/src/Components/Content/OrganizationInformation/ViewEditOrganizationEmail.tsx
  front-end/src/Components/Content/OrganizationInformation/ViewEditOrganizationName.tsx
  front-end/src/Components/Content/OrganizationInformation/ViewEditOrganizationPhone.tsx
  front-end/src/Components/Content/OrganizationInformation/ViewEditOrganizationPhoto.tsx
  front-end/src/Components/Layouts/CreateEvent.tsx
  front-end/src/Components/Layouts/CreateEventDialog.tsx
  front-end/src/Components/Layouts/EditOrganization.tsx
  front-end/src/Components/Layouts/Organization.tsx
  front-end/src/Components/Layouts/OrganizationEvents.tsx
  front-end/src/Components/Pages/ManageOrganizations.tsx
  front-end/src/Components/Pages/index.ts
  front-end/src/Scripts/firebaseConfig.ts
  front-end/src/Scripts/firebaseCreateNewOrganization.ts
  front-end/src/Scripts/firebaseGetEvents.ts
  front-end/src/Scripts/firebaseGetOrganizations.ts
  front-end/src/Scripts/firebaseOrganizationTypes.d.ts
  front-end/src/Scripts/firebaseOrganizationUpdates.ts
Labels: bug, enhancement
